# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
# RUN elasticsearch-plugin install mobz/elasticsearch-head DEPRACTED IN 5
# docker run -p 9100:9100 mobz/elasticsearch-head:5
RUN elasticsearch-plugin install analysis-icu
